title: "My Portfolio"
author: "Hamid Manouchehri"
excerpt_separator: "\n\n\n"
description: "Robotic Engineer & Researcher"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "_posts/2022-09-22-about_me.md", icon: user, title: "Bio"}
#   - {file: "README.md", icon: robot, title: "Projects"}
#   - {file: "CV_22Sep2022.pdf", icon: file-pdf, title: "Vita"}
#   - {file: <embed src=https://Hamid-Manouchehri.github.io/CV_22Sep2022.pdf type="application/pdf"/>, icon: file-pdf, title: "Vita"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Bio, icon: user, url: "/_posts/2022-09-22-about_me.md"}
  - {title: Projects, icon: robot, url: "/Projects.html"}
  - {title: Vita, icon: file-pdf, url: "/pdf_files/CV_v4_Hamid_Manouchehri_blog_added.pdf"}
  - {title: Mail, icon: envelope, url: "mailto:hamid.manouchehri.njf@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Hamid-Manouchehri"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/hamid-manouchehri"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Hamid-Manouchehri-2"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
