title: "My Portfolio"
author: "Hamid Manouchehri"
excerpt_separator: "\n\n\n"
description: "Robotic Engineer & Researcher"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", icon: user, title: "Bio"}
  - {file: "README.md", icon: robot, title: "Projects"}
  - {file: "CV_22Sep2022.pdf", icon: file-pdf, title: "Vita"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:hamid.manouchehri.njf@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Hamid-Manouchehri"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/hamid-manouchehri"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Hamid-Manouchehri-2"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
