# Configuration of sidebar panel and initial web page:
title: "My Portfolio"
author: "Hamid Manouchehri"
excerpt_separator: "\n\n\n"
description: "<br><br><br> <small style=\"color: #f45;\"> Mechatronics Engineer & Robotics Researcher: Dynamics, Control and Software </small>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: Hamid Manouchehri, icon: user, file: "README.md"}  # It must be `README.md` for initial loading of the portfolio
 
  - {title: Projects, icon: robot, file: "projects.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Vita, icon: file-pdf, url: "/pdf_files/CV_v4_Hamid_Manouchehri_blog_added.pdf"}
  - {title: Mail, icon: envelope, url: "mailto:hamid.manouchehri.njf@gmail.com"}
  - {title: GitHub, icon: github, url: "https://github.com/Hamid-Manouchehri"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/hamid-manouchehri"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Hamid-Manouchehri-2"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
