<html lang="zxx">
<head>
    <title>Mohammadreza Nakhaei, Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" />
    <meta name="keywords" content="cv, deep reinforcement learning, robotics" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- Custom Theme files -->
    <link href="css/bootstrap.css" type="text/css" rel="stylesheet" media="all">
    <link href="css/style.css" type="text/css" rel="stylesheet" media="all">
    <!-- font-awesome icons -->
    <link href="css/fontawesome-all.min.css" rel="stylesheet">
    <!-- //Custom Theme files -->
    <!-- online-fonts -->
	<link href="//fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">
   <!-- //online-fonts -->

</head>

title: "My Portfolio"
author: "Hamid Manouchehri"
excerpt_separator: "\n\n\n"
description: "Robotic Engineer & Researcher"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "", file: ""}
#   - {file: "README.md", icon: robot, title: "Projects"}
#   - {file: "CV_22Sep2022.pdf", icon: file-pdf, title: "Vita"}
#   - {file: <embed src=https://Hamid-Manouchehri.github.io/CV_22Sep2022.pdf type="application/pdf"/>, icon: file-pdf, title: "Vita"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Hamid Manouchehri Robotic Engineer & Researcher}
  - {title: Projects, icon: robot, url: "/projects/projects.html"}
  - {title: Vita, icon: file-pdf, url: "/pdf_files/CV_v4_Hamid_Manouchehri_blog_added.pdf"}
  - {title: Mail, icon: envelope, url: "mailto:hamid.manouchehri.njf@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Hamid-Manouchehri"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/hamid-manouchehri"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Hamid-Manouchehri-2"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
